---
title: "Assignment 1"
author: "Huang Yingshan, Kahlbacher Fabian, Wattenberg Yannick, Aggeler Samuel"
date: "10/17/2021"
output: html_document
---

```{r setup, include=FALSE}

set.seed(1908)
library(sna)
library(network)
obsMat <- as.matrix(read.csv("matrix.csv"))
cguRec1 <- cug.test(obsMat, grecip, cmode = "edges", reps = 3000)
cguRec2 <- cug.test(obsMat, grecip, cmode = "dyad.census", reps = 3000)
cugTrans <- cug.test(obsMat, gtrans, cmode = "dyad.census",  reps = 3000)
cguRec1
cguRec2
cugTrans



```




# Task 1
## 1) /( /frac{174}{35*34) /)


# Task 2

```{r}
set.seed(1908)
permutations <- 5000
trade2006 <- as.matrix(read.csv("trade1.csv", header=FALSE))
trade2007 <- as.matrix(read.csv("trade2.csv", header=FALSE))
attr <- read.csv("attr.csv")
nl0 <- netlm(trade2007, trade2006, rep=permutations, nullhyp="qapy")
summary(nl0)

##### 2

sector <- attr[,2]
sameSector <- outer(sector,sector,"==")*1
diag(sameSector) <- FALSE

SectorSender <- matrix(sector,18,18,byrow=FALSE) # Hp. 2

zm <- list(SectorSender, sameSector)
nl <- netlm(trade2007, zm, rep=permutations, nullhyp="qapspp")
nl$names <- c("intercept", "sameSector", "SectorSender")
```
